version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniforge3-latest"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

formats: all

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/environment.yml